apiVersion: apps/v1
kind: Deployment
metadata:
  name:  scrum-dhaka-hirok
  namespace: demo
spec:
  selector:
    matchLabels:
      app: scrum-dhaka-hirok
  template:
    metadata:
      labels:
        app: scrum-dhaka-hirok
    spec:
      containers:
        - name: scrum-dhaka-hirok
          image: hiroksarker/scrum-dhaka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000